
networks:
  inception:
    name: inception

services:
  ningx:
    container_name: nginx
    build:
      context: ./requirements/nginx/.
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env_general
    volumes:
      - wp-data:/domains
    restart: always


volumes:
  wp-data:
    driver_opts:
      type: none
      device: /home/jcallejo/data/volumes/web
      o: bind

  db-data:
    driver_opts:
      type: none
      device: /home/jcallejo/data/volumes/db
      o: bind
