
networks:
  inception:
    name: inception

services:
  ningx:
    container_name: nginx
    build:
      context: ./requirements/nginx/.
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env_general
    volumes:
      - wp-data:/domains
    restart: always

